# Generated by Django 4.1 on 2022-09-08 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('parentesco', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('cumpleanios', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
